repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [-m]
        files: '.*.ya?ml'
      - id: check-added-large-files
      - id: check-merge-conflict

  # - repo: https://github.com/bjd2385/circleci-config-pre-commit-hook
  #   rev: v1.0.3
  #   hooks:
  #     - id: circleci-config-validate
