redis:
  kubeVersion: 1.24.1
  architecture: replication

  master: {}

  replica:
    replicaCount: 2

    containerPorts:
      redis: 6379

  volumePermissions:
    enabled: true

  metrics:
    enabled: false
